### ISSUE TITLE
Blank window when opening existing, or creating new image (version 0.1.0)

### ISSUE THREAD

**Issue by Randalphwa** [Tyriar/vscode-luna-paint#1]
I have verified that the extension is loaded and enabled globally. There is nothing displayed in the window when either opening a small (22x22) png file, or creating a new (64x64) image. I copied current editor data below, let me know if there's anything else I can provide.

Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
There might be an issue creating the webgl context, can you check the devtools console for errors? (Help > Toggle Developer Tools)

If that doesn't show anything, can you open a file and check the webview devtools for errors as well by running the following command through the command palette (F1):

![image](https://user-images.githubusercontent.com/2193314/103604239-58c8a380-4ec5-11eb-9d10-4434d360d87c.png)

**Comment by Randalphwa** [comment]
Dev tools reports when I open a file:

webviewElement.ts:90 [Embedded Page] Uncaught SyntaxError: Unexpected token '='

Same error when I try to create a new issue.

**Comment by Tyriar** [comment]
Thanks a bunch for the report, this is fixed and published 👍
