### ISSUE TITLE
Configure brush size?

### ISSUE THREAD

**Issue by JacksonKearl** [Tyriar/vscode-luna-paint#16]
Is there any way to configure the brush size of the pencil and eraser?

**Comment by Tyriar** [comment]
Eraser does just above the tool window, the plan is to keep pencil as 1x1 and introduce a paint brush with configurable size

![image](https://user-images.githubusercontent.com/2193314/104673117-eeb6b800-5695-11eb-813e-c1ffaddccd67.png)

**Comment by Tyriar** [comment]
Created https://github.com/Tyriar/vscode-luna-paint/issues/20 to capture that
