### ISSUE TITLE
"The Image was Deleted on disk" notification when I delete via explorer

### ISSUE THREAD

**Issue by JacksonKearl** [Tyriar/vscode-luna-paint#18]
1. Select Image in explorer
2. Custom editor appears
2. Delete it, editor disappears.
3. notification pops up saying the image was deleted on disk. 

I know it was deleted, I just deleted it 🙂 but now I need to close a notification too

**Comment by Tyriar** [comment]
Good call. This was added because the tab in custom editors doesn't display (deleted), it does show the git decoration in a window though:

![image](https://user-images.githubusercontent.com/2193314/104958217-7b0df700-5984-11eb-8a25-3a258601acf5.png)

**Comment by Tyriar** [comment]
Vscode issue: https://github.com/microsoft/vscode/issues/114545
