### ISSUE TITLE
Support for a grid overlay

### ISSUE THREAD

**Issue by zignd** [Tyriar/vscode-luna-paint#5]
Hi there,

This extension is pretty awesome, but I'd love to have support for some sort of grid overlay to help me do some pixel art more precisely. Image editors like Asesprite and Pixelorama provide that, even though they are specialized on pixel art. Is this possible on Luna?

Here are some screenshots to describe what I mean:

![image](https://user-images.githubusercontent.com/3194806/103642866-88fa5b80-4f32-11eb-83bb-a86377601df9.png)
(Asesprite)

![image](https://user-images.githubusercontent.com/3194806/103642191-919e6200-4f31-11eb-9af1-5f0056f6c793.png)
(Pixelorama)

![image](https://user-images.githubusercontent.com/3194806/103641587-ba722780-4f30-11eb-8b3f-7c0942bc3354.png)
(Luna)

**Comment by Tyriar** [comment]
I'll bump up the priority to hopefully get this in the next version since you're asking 🙂.

Also sweet duck 🦆

**Comment by zignd** [comment]
Thanks Tyriar! It looks like I'm a terrible artist, it was supposed to chicken :rofl:
